; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 12 2020 14:28:45 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA1ZG7XTTMFRS:
	dc.w DATA1ZG7XTTMFRS_0-DATA1ZG7XTTMFRS, DATA1ZG7XTTMFRS_1-DATA1ZG7XTTMFRS
	dc.w DATA1ZG7XTTMFRS_2-DATA1ZG7XTTMFRS, DATA1ZG7XTTMFRS_3-DATA1ZG7XTTMFRS
	dc.w DATA1ZG7XTTMFRS_4-DATA1ZG7XTTMFRS, DATA1ZG7XTTMFRS_5-DATA1ZG7XTTMFRS
DATA1ZG7XTTMFRS_0: dc.b $6
	dc.b $EE, $5, $0, $0, $F0
	dc.b $EE, $5, $8, $0, $0
	dc.b $FE, $5, $0, $4, $F0
	dc.b $FE, $5, $8, $4, $0
	dc.b $E, $4, $0, $8, $F0
	dc.b $E, $4, $8, $8, $0
DATA1ZG7XTTMFRS_1: dc.b $6
	dc.b $EE, $5, $0, $0, $F0
	dc.b $EE, $5, $8, $0, $0
	dc.b $FE, $5, $0, $4, $F0
	dc.b $FE, $5, $8, $4, $0
	dc.b $E, $4, $8, $8, $0
	dc.b $E, $4, $0, $A, $F0
DATA1ZG7XTTMFRS_2: dc.b $6
	dc.b $EE, $5, $8, $0, $0
	dc.b $EE, $5, $0, $0, $F0
	dc.b $FE, $5, $8, $4, $0
	dc.b $FE, $5, $0, $4, $F0
	dc.b $E, $4, $0, $8, $F0
	dc.b $E, $4, $8, $A, $0
DATA1ZG7XTTMFRS_3: dc.b $6
	dc.b $EE, $5, $0, $0, $F0
	dc.b $EE, $5, $8, $0, $0
	dc.b $E, $4, $0, $8, $F0
	dc.b $E, $4, $8, $8, $0
	dc.b $FE, $5, $0, $C, $F0
	dc.b $FE, $5, $8, $C, $0
DATA1ZG7XTTMFRS_4: dc.b $1
	dc.b $F8, $5, $0, $10, $F8
DATA1ZG7XTTMFRS_5: dc.b $1
	dc.b $F8, $5, $0, $14, $F8
	even