; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri May 29 2020 06:29:32 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAGFGPVF5XIC:
	dc.w DATAGFGPVF5XIC_0-DATAGFGPVF5XIC, DATAGFGPVF5XIC_1-DATAGFGPVF5XIC
	dc.w DATAGFGPVF5XIC_2-DATAGFGPVF5XIC, DATAGFGPVF5XIC_3-DATAGFGPVF5XIC
	dc.w DATAGFGPVF5XIC_4-DATAGFGPVF5XIC, DATAGFGPVF5XIC_5-DATAGFGPVF5XIC
	dc.w DATAGFGPVF5XIC_6-DATAGFGPVF5XIC, DATAGFGPVF5XIC_7-DATAGFGPVF5XIC
	dc.w DATAGFGPVF5XIC_8-DATAGFGPVF5XIC, DATAGFGPVF5XIC_9-DATAGFGPVF5XIC
	dc.w DATAGFGPVF5XIC_A-DATAGFGPVF5XIC
DATAGFGPVF5XIC_0: dc.b $2
	dc.b $F4, $6, $20, $0, $F8
	dc.b $C, $4, $20, $31, $F8
DATAGFGPVF5XIC_1: dc.b $3
	dc.b $F4, $6, $20, $0, $F8
	dc.b $C, $0, $20, $4D, $FC
	dc.b $C, $4, $20, $31, $F8
DATAGFGPVF5XIC_2: dc.b $3
	dc.b $F2, $E, $20, $6, $F4
	dc.b $A, $4, $20, $12, $FC
	dc.b $A, $0, $20, $33, $F4
DATAGFGPVF5XIC_3: dc.b $9
	dc.b $F2, $4, $20, $14, $F9
	dc.b $FA, $C, $20, $16, $F1
	dc.b $2, $4, $20, $1A, $1
	dc.b $A, $4, $20, $20, $1
	dc.b $2, $0, $20, $1C, $F1
	dc.b $A, $0, $20, $1D, $F1
	dc.b $2, $0, $20, $1E, $F9
	dc.b $A, $0, $20, $1F, $F9
	dc.b $F2, $0, $A0, $34, $F1
DATAGFGPVF5XIC_4: dc.b $2
	dc.b $F2, $B, $20, $22, $F6
	dc.b $12, $8, $20, $2E, $F6
DATAGFGPVF5XIC_5: dc.b $4
	dc.b $F7, $0, $20, $4E, $F8
	dc.b $F2, $E, $20, $6, $F4
	dc.b $A, $4, $20, $12, $FC
	dc.b $A, $0, $20, $33, $F4
DATAGFGPVF5XIC_6: dc.b $A
	dc.b $F7, $0, $20, $4E, $F8
	dc.b $F2, $4, $20, $14, $F9
	dc.b $FA, $C, $20, $16, $F1
	dc.b $2, $4, $20, $1A, $1
	dc.b $A, $4, $20, $20, $1
	dc.b $2, $0, $20, $1C, $F1
	dc.b $A, $0, $20, $1D, $F1
	dc.b $2, $0, $20, $1E, $F9
	dc.b $A, $0, $20, $1F, $F9
	dc.b $F2, $0, $A0, $34, $F1
DATAGFGPVF5XIC_7: dc.b $3
	dc.b $F7, $0, $20, $4E, $F8
	dc.b $F2, $B, $20, $22, $F6
	dc.b $12, $8, $20, $2E, $F6
DATAGFGPVF5XIC_8: dc.b $1
	dc.b $F8, $D, $0, $35, $F0
DATAGFGPVF5XIC_9: dc.b $1
	dc.b $F8, $D, $0, $45, $F0
DATAGFGPVF5XIC_A: dc.b $1
	dc.b $F8, $D, $0, $3D, $F0
	even