; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Sep 29 2020 10:50:18 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA5TVPNJ0F4D:
	dc.w DATA5TVPNJ0F4D_0-DATA5TVPNJ0F4D, DATA5TVPNJ0F4D_1-DATA5TVPNJ0F4D
	dc.w DATA5TVPNJ0F4D_2-DATA5TVPNJ0F4D, DATA5TVPNJ0F4D_3-DATA5TVPNJ0F4D
	dc.w DATA5TVPNJ0F4D_4-DATA5TVPNJ0F4D, DATA5TVPNJ0F4D_5-DATA5TVPNJ0F4D
	dc.w DATA5TVPNJ0F4D_6-DATA5TVPNJ0F4D, DATA5TVPNJ0F4D_7-DATA5TVPNJ0F4D
	dc.w DATA5TVPNJ0F4D_8-DATA5TVPNJ0F4D, DATA5TVPNJ0F4D_9-DATA5TVPNJ0F4D
	dc.w DATA5TVPNJ0F4D_A-DATA5TVPNJ0F4D, DATA5TVPNJ0F4D_B-DATA5TVPNJ0F4D
	dc.w DATA5TVPNJ0F4D_C-DATA5TVPNJ0F4D
DATA5TVPNJ0F4D_0: dc.b $2
	dc.b $F4, $6, $20, $0, $F8
	dc.b $C, $4, $20, $31, $F8
DATA5TVPNJ0F4D_1: dc.b $3
	dc.b $F2, $E, $20, $6, $F4
	dc.b $A, $4, $20, $12, $FC
	dc.b $A, $0, $20, $33, $F4
DATA5TVPNJ0F4D_2: dc.b $9
	dc.b $F2, $4, $20, $14, $F9
	dc.b $FA, $C, $20, $16, $F1
	dc.b $2, $4, $20, $1A, $1
	dc.b $A, $4, $20, $20, $1
	dc.b $2, $0, $20, $1C, $F1
	dc.b $A, $0, $20, $1D, $F1
	dc.b $2, $0, $20, $1E, $F9
	dc.b $A, $0, $20, $1F, $F9
	dc.b $F2, $0, $A0, $34, $F1
DATA5TVPNJ0F4D_3: dc.b $2
	dc.b $F2, $B, $20, $22, $F6
	dc.b $12, $8, $20, $2E, $F6
DATA5TVPNJ0F4D_4: dc.b $3
	dc.b $F3, $E, $20, $6, $F4
	dc.b $B, $4, $20, $12, $FC
	dc.b $B, $0, $20, $33, $F4
DATA5TVPNJ0F4D_5: dc.b $9
	dc.b $F3, $4, $20, $14, $F9
	dc.b $FB, $C, $20, $16, $F1
	dc.b $3, $4, $20, $1A, $1
	dc.b $B, $4, $20, $20, $1
	dc.b $3, $0, $20, $1C, $F1
	dc.b $B, $0, $20, $1D, $F1
	dc.b $3, $0, $20, $1E, $F9
	dc.b $B, $0, $20, $1F, $F9
	dc.b $F3, $0, $A0, $34, $F1
DATA5TVPNJ0F4D_6: dc.b $2
	dc.b $F3, $B, $20, $22, $F6
	dc.b $13, $8, $20, $2E, $F6
DATA5TVPNJ0F4D_7: dc.b $3
	dc.b $F4, $E, $20, $6, $F4
	dc.b $C, $4, $20, $12, $FC
	dc.b $C, $0, $20, $33, $F4
DATA5TVPNJ0F4D_8: dc.b $9
	dc.b $F4, $4, $20, $14, $F9
	dc.b $FC, $C, $20, $16, $F1
	dc.b $4, $4, $20, $1A, $1
	dc.b $C, $4, $20, $20, $1
	dc.b $4, $0, $20, $1C, $F1
	dc.b $C, $0, $20, $1D, $F1
	dc.b $4, $0, $20, $1E, $F9
	dc.b $C, $0, $20, $1F, $F9
	dc.b $F4, $0, $A0, $34, $F1
DATA5TVPNJ0F4D_9: dc.b $2
	dc.b $F4, $B, $20, $22, $F6
	dc.b $14, $8, $20, $2E, $F6
DATA5TVPNJ0F4D_A: dc.b $1
	dc.b $F8, $D, $0, $35, $F0
DATA5TVPNJ0F4D_B: dc.b $1
	dc.b $F8, $D, $0, $45, $F0
DATA5TVPNJ0F4D_C: dc.b $1
	dc.b $F8, $D, $0, $3D, $F0
	even