; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Sep 11 2020 19:55:41 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAACI5E2PUVKV:
	dc.w DATAACI5E2PUVKV_0-DATAACI5E2PUVKV, DATAACI5E2PUVKV_1-DATAACI5E2PUVKV
	dc.w DATAACI5E2PUVKV_2-DATAACI5E2PUVKV, DATAACI5E2PUVKV_3-DATAACI5E2PUVKV
	dc.w DATAACI5E2PUVKV_4-DATAACI5E2PUVKV, DATAACI5E2PUVKV_5-DATAACI5E2PUVKV
	dc.w DATAACI5E2PUVKV_6-DATAACI5E2PUVKV, DATAACI5E2PUVKV_7-DATAACI5E2PUVKV
	dc.w DATAACI5E2PUVKV_8-DATAACI5E2PUVKV, DATAACI5E2PUVKV_9-DATAACI5E2PUVKV
	dc.w DATAACI5E2PUVKV_A-DATAACI5E2PUVKV
DATAACI5E2PUVKV_0: dc.b $2
	dc.b $F4, $6, $20, $0, $F8
	dc.b $C, $4, $20, $31, $F8
DATAACI5E2PUVKV_1: dc.b $2
	dc.b $F4, $6, $20, $0, $F8
	dc.b $C, $4, $20, $31, $F8
DATAACI5E2PUVKV_2: dc.b $3
	dc.b $F2, $E, $20, $6, $F4
	dc.b $A, $4, $20, $12, $FC
	dc.b $A, $0, $20, $33, $F4
DATAACI5E2PUVKV_3: dc.b $9
	dc.b $F2, $4, $20, $14, $F9
	dc.b $FA, $C, $20, $16, $F1
	dc.b $2, $4, $20, $1A, $1
	dc.b $A, $4, $20, $20, $1
	dc.b $2, $0, $20, $1C, $F1
	dc.b $A, $0, $20, $1D, $F1
	dc.b $2, $0, $20, $1E, $F9
	dc.b $A, $0, $20, $1F, $F9
	dc.b $F2, $0, $A0, $34, $F1
DATAACI5E2PUVKV_4: dc.b $2
	dc.b $F2, $B, $20, $22, $F6
	dc.b $12, $8, $20, $2E, $F6
DATAACI5E2PUVKV_5: dc.b $3
	dc.b $F2, $E, $20, $6, $F4
	dc.b $A, $4, $20, $12, $FC
	dc.b $A, $0, $20, $33, $F4
DATAACI5E2PUVKV_6: dc.b $9
	dc.b $F2, $4, $20, $14, $F9
	dc.b $FA, $C, $20, $16, $F1
	dc.b $2, $4, $20, $1A, $1
	dc.b $A, $4, $20, $20, $1
	dc.b $2, $0, $20, $1C, $F1
	dc.b $A, $0, $20, $1D, $F1
	dc.b $2, $0, $20, $1E, $F9
	dc.b $A, $0, $20, $1F, $F9
	dc.b $F2, $0, $A0, $34, $F1
DATAACI5E2PUVKV_7: dc.b $2
	dc.b $F2, $B, $20, $22, $F6
	dc.b $12, $8, $20, $2E, $F6
DATAACI5E2PUVKV_8: dc.b $1
	dc.b $F8, $D, $0, $35, $F0
DATAACI5E2PUVKV_9: dc.b $1
	dc.b $F8, $D, $0, $45, $F0
DATAACI5E2PUVKV_A: dc.b $1
	dc.b $F8, $D, $0, $3D, $F0
	even