; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri May 29 2020 00:04:10 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAG4F2NXXPO57:
	dc.w DATAG4F2NXXPO57_0-DATAG4F2NXXPO57, DATAG4F2NXXPO57_1-DATAG4F2NXXPO57
	dc.w DATAG4F2NXXPO57_2-DATAG4F2NXXPO57, DATAG4F2NXXPO57_3-DATAG4F2NXXPO57
	dc.w DATAG4F2NXXPO57_4-DATAG4F2NXXPO57, DATAG4F2NXXPO57_5-DATAG4F2NXXPO57
DATAG4F2NXXPO57_0: dc.b $2
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $C, $0, $10, $F0
DATAG4F2NXXPO57_1: dc.b $2
	dc.b $F4, $F, $0, $14, $F0
	dc.b $EC, $C, $0, $24, $F0
DATAG4F2NXXPO57_2: dc.b $2
	dc.b $F8, $F, $0, $28, $F0
	dc.b $F0, $C, $0, $38, $F0
DATAG4F2NXXPO57_3: dc.b $1
	dc.b $EC, $F, $0, $3C, $F0
DATAG4F2NXXPO57_4: dc.b $3
	dc.b $F4, $E, $88, $4C, $F8
	dc.b $C, $C, $88, $58, $F8
	dc.b $F4, $3, $88, $5C, $F0
DATAG4F2NXXPO57_5: dc.b $3
	dc.b $F4, $E, $80, $4C, $EE
	dc.b $C, $C, $80, $58, $EE
	dc.b $F4, $3, $80, $5C, $E
	even