; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jun 03 2020 05:48:48 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAQ3KRBUSIUZL:
	dc.w DATAQ3KRBUSIUZL_0-DATAQ3KRBUSIUZL, DATAQ3KRBUSIUZL_1-DATAQ3KRBUSIUZL
DATAQ3KRBUSIUZL_0: dc.b $1
	dc.b $F0, $F, $20, $0, $F0
DATAQ3KRBUSIUZL_1: dc.b $1
	dc.b $F0, $F, $20, $10, $F0
	even