; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Mar 14 2020 04:49:23 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAH6D6RBZHVUA:
	dc.w DATAH6D6RBZHVUA_0-DATAH6D6RBZHVUA, DATAH6D6RBZHVUA_1-DATAH6D6RBZHVUA
	dc.w DATAH6D6RBZHVUA_2-DATAH6D6RBZHVUA, DATAH6D6RBZHVUA_3-DATAH6D6RBZHVUA
	dc.w DATAH6D6RBZHVUA_4-DATAH6D6RBZHVUA, DATAH6D6RBZHVUA_5-DATAH6D6RBZHVUA
	dc.w DATAH6D6RBZHVUA_6-DATAH6D6RBZHVUA, DATAH6D6RBZHVUA_7-DATAH6D6RBZHVUA
DATAH6D6RBZHVUA_0: dc.b $6
	dc.b $F8, $D, $0, $25, $A8
	dc.b $F8, $D, $0, $2D, $C8
	dc.b $F8, $D, $0, $35, $E8
	dc.b $F8, $D, $0, $3D, $8
	dc.b $F8, $D, $0, $45, $28
	dc.b $F8, $5, $0, $4D, $48
DATAH6D6RBZHVUA_1: dc.b $3
	dc.b $4, $5, $0, $15, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATAH6D6RBZHVUA_2: dc.b $3
	dc.b $4, $5, $0, $19, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATAH6D6RBZHVUA_3: dc.b $3
	dc.b $4, $5, $0, $1D, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATAH6D6RBZHVUA_4: dc.b $2
	dc.b $60, $9, $20, $0, $E8
	dc.b $60, $9, $28, $0, $0
DATAH6D6RBZHVUA_5: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATAH6D6RBZHVUA_6: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATAH6D6RBZHVUA_7: dc.b $1
	dc.b $0, $6, $0, $18, $0
	even