; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Sep 05 2020 23:06:00 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAXGCA2ADWGSR:
	dc.w DATAXGCA2ADWGSR_0-DATAXGCA2ADWGSR, DATAXGCA2ADWGSR_1-DATAXGCA2ADWGSR
	dc.w DATAXGCA2ADWGSR_2-DATAXGCA2ADWGSR, DATAXGCA2ADWGSR_3-DATAXGCA2ADWGSR
	dc.w DATAXGCA2ADWGSR_4-DATAXGCA2ADWGSR, DATAXGCA2ADWGSR_5-DATAXGCA2ADWGSR
	dc.w DATAXGCA2ADWGSR_6-DATAXGCA2ADWGSR, DATAXGCA2ADWGSR_7-DATAXGCA2ADWGSR
DATAXGCA2ADWGSR_0: dc.b $5
	dc.b $F8, $D, $0, $25, $BC
	dc.b $F8, $D, $0, $2D, $DC
	dc.b $F8, $D, $0, $35, $FC
	dc.b $F8, $D, $0, $3D, $1C
	dc.b $F8, $1, $0, $45, $3C
DATAXGCA2ADWGSR_1: dc.b $3
	dc.b $4, $5, $0, $15, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATAXGCA2ADWGSR_2: dc.b $3
	dc.b $4, $5, $0, $19, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATAXGCA2ADWGSR_3: dc.b $3
	dc.b $4, $5, $0, $1D, $FB
	dc.b $F4, $A, $0, $6, $EC
	dc.b $F4, $6, $0, $F, $4
DATAXGCA2ADWGSR_4: dc.b $2
	dc.b $60, $9, $20, $0, $E8
	dc.b $60, $9, $28, $0, $0
DATAXGCA2ADWGSR_5: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATAXGCA2ADWGSR_6: dc.b $1
	dc.b $0, $6, $0, $12, $0
DATAXGCA2ADWGSR_7: dc.b $1
	dc.b $0, $6, $0, $18, $0
	even