; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jun 03 2020 04:54:12 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATADSG50QY5RY:
	dc.w DATADSG50QY5RY_0-DATADSG50QY5RY, DATADSG50QY5RY_1-DATADSG50QY5RY
	dc.w DATADSG50QY5RY_2-DATADSG50QY5RY, DATADSG50QY5RY_3-DATADSG50QY5RY
	dc.w DATADSG50QY5RY_4-DATADSG50QY5RY, DATADSG50QY5RY_5-DATADSG50QY5RY
	dc.w DATADSG50QY5RY_6-DATADSG50QY5RY, DATADSG50QY5RY_7-DATADSG50QY5RY
	dc.w DATADSG50QY5RY_8-DATADSG50QY5RY, DATADSG50QY5RY_9-DATADSG50QY5RY
	dc.w DATADSG50QY5RY_A-DATADSG50QY5RY, DATADSG50QY5RY_B-DATADSG50QY5RY
	dc.w DATADSG50QY5RY_C-DATADSG50QY5RY
DATADSG50QY5RY_0: dc.b $6
	dc.b $EC, $1, $0, $A, $E4
	dc.b $EC, $5, $0, $C, $C
	dc.b $FC, $E, $20, $10, $E4
	dc.b $FC, $E, $20, $1C, $4
	dc.b $14, $C, $20, $28, $EC
	dc.b $14, $0, $20, $2C, $C
DATADSG50QY5RY_1: dc.b $2
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $2, $EC
DATADSG50QY5RY_2: dc.b $2
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $35, $EC
DATADSG50QY5RY_3: dc.b $3
	dc.b $E4, $8, $0, $3D, $F4
	dc.b $EC, $9, $0, $40, $EC
	dc.b $EC, $5, $0, $46, $4
DATADSG50QY5RY_4: dc.b $3
	dc.b $E4, $8, $0, $4A, $F4
	dc.b $EC, $9, $0, $4D, $EC
	dc.b $EC, $5, $0, $53, $4
DATADSG50QY5RY_5: dc.b $3
	dc.b $E4, $8, $0, $57, $F4
	dc.b $EC, $9, $0, $5A, $EC
	dc.b $EC, $5, $0, $60, $4
DATADSG50QY5RY_6: dc.b $3
	dc.b $E4, $4, $0, $64, $4
	dc.b $E4, $4, $0, $0, $F4
	dc.b $EC, $D, $0, $35, $EC
DATADSG50QY5RY_7: dc.b $4
	dc.b $E4, $9, $0, $66, $F4
	dc.b $E4, $8, $0, $57, $F4
	dc.b $EC, $9, $0, $5A, $EC
	dc.b $EC, $5, $0, $60, $4
DATADSG50QY5RY_8: dc.b $1
	dc.b $4, $5, $0, $2D, $22
DATADSG50QY5RY_9: dc.b $1
	dc.b $4, $5, $0, $31, $22
DATADSG50QY5RY_A: dc.b $0
DATADSG50QY5RY_B: dc.b $2
	dc.b $0, $8, $1, $2A, $22
	dc.b $8, $8, $11, $2A, $22
DATADSG50QY5RY_C: dc.b $2
	dc.b $F8, $B, $1, $2D, $22
	dc.b $0, $1, $1, $39, $3A
	even