; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 12 2020 17:52:06 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAU4EAYIJUFJR:
	dc.w DATAU4EAYIJUFJR_0-DATAU4EAYIJUFJR, DATAU4EAYIJUFJR_1-DATAU4EAYIJUFJR
	dc.w DATAU4EAYIJUFJR_2-DATAU4EAYIJUFJR, DATAU4EAYIJUFJR_3-DATAU4EAYIJUFJR
	dc.w DATAU4EAYIJUFJR_4-DATAU4EAYIJUFJR, DATAU4EAYIJUFJR_5-DATAU4EAYIJUFJR
	dc.w DATAU4EAYIJUFJR_6-DATAU4EAYIJUFJR, DATAU4EAYIJUFJR_7-DATAU4EAYIJUFJR
DATAU4EAYIJUFJR_0: dc.b $A
	dc.b $E0, $8, $0, $0, $E8
	dc.b $E0, $8, $0, $3, $0
	dc.b $E8, $C, $0, $6, $E0
	dc.b $E8, $C, $0, $A, $0
	dc.b $F0, $7, $0, $E, $E0
	dc.b $F0, $7, $0, $16, $10
	dc.b $10, $C, $0, $1E, $E0
	dc.b $10, $C, $0, $22, $0
	dc.b $18, $8, $0, $26, $E8
	dc.b $18, $8, $0, $29, $0
DATAU4EAYIJUFJR_1: dc.b $A
	dc.b $E0, $8, $0, $0, $E8
	dc.b $E0, $8, $0, $3, $0
	dc.b $E8, $C, $0, $6, $E0
	dc.b $E8, $C, $0, $A, $0
	dc.b $F0, $7, $0, $E, $E0
	dc.b $F0, $7, $0, $16, $10
	dc.b $10, $C, $0, $1E, $E0
	dc.b $10, $C, $0, $22, $0
	dc.b $18, $8, $0, $26, $E8
	dc.b $18, $8, $0, $29, $0
DATAU4EAYIJUFJR_2: dc.b $8
	dc.b $E0, $C, $0, $2C, $F0
	dc.b $E8, $8, $0, $30, $E8
	dc.b $E8, $9, $0, $33, $0
	dc.b $F0, $7, $0, $39, $E8
	dc.b $F8, $5, $0, $41, $8
	dc.b $8, $9, $0, $45, $0
	dc.b $10, $8, $0, $4B, $E8
	dc.b $18, $C, $0, $4E, $F0
DATAU4EAYIJUFJR_3: dc.b $8
	dc.b $E0, $C, $0, $2C, $F0
	dc.b $E8, $8, $0, $30, $E8
	dc.b $E8, $9, $0, $33, $0
	dc.b $F0, $7, $0, $39, $E8
	dc.b $F8, $5, $0, $41, $8
	dc.b $8, $9, $0, $45, $0
	dc.b $10, $8, $0, $4B, $E8
	dc.b $18, $C, $0, $4E, $F0
DATAU4EAYIJUFJR_4: dc.b $4
	dc.b $E0, $7, $0, $52, $F4
	dc.b $E0, $3, $8, $52, $4
	dc.b $0, $7, $0, $5A, $F4
	dc.b $0, $3, $8, $5A, $4
DATAU4EAYIJUFJR_5: dc.b $4
	dc.b $E0, $7, $0, $52, $F4
	dc.b $E0, $3, $8, $52, $4
	dc.b $0, $7, $0, $5A, $F4
	dc.b $0, $3, $8, $5A, $4
DATAU4EAYIJUFJR_6: dc.b $8
	dc.b $E0, $C, $8, $2C, $F0
	dc.b $E8, $8, $8, $30, $0
	dc.b $E8, $9, $8, $33, $E8
	dc.b $F0, $7, $8, $39, $8
	dc.b $F8, $5, $8, $41, $E8
	dc.b $8, $9, $8, $45, $E8
	dc.b $10, $8, $8, $4B, $0
	dc.b $18, $C, $8, $4E, $F0
DATAU4EAYIJUFJR_7: dc.b $8
	dc.b $E0, $C, $8, $2C, $F0
	dc.b $E8, $8, $8, $30, $0
	dc.b $E8, $9, $8, $33, $E8
	dc.b $F0, $7, $8, $39, $8
	dc.b $F8, $5, $8, $41, $E8
	dc.b $8, $9, $8, $45, $E8
	dc.b $10, $8, $8, $4B, $0
	dc.b $18, $C, $8, $4E, $F0
	even