; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Sep 19 2020 11:22:51 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAKOCW78LZQD:
	dc.w DATAKOCW78LZQD_0-DATAKOCW78LZQD, DATAKOCW78LZQD_1-DATAKOCW78LZQD
	dc.w DATAKOCW78LZQD_2-DATAKOCW78LZQD, DATAKOCW78LZQD_3-DATAKOCW78LZQD
DATAKOCW78LZQD_0: dc.b $9
	dc.b $80, $D, $A0, $0, $F8
	dc.b $80, $D, $A0, $18, $18
	dc.b $80, $D, $80, $20, $38
	dc.b $90, $D, $A0, $8, $F8
	dc.b $90, $9, $80, $30, $28
	dc.b $41, $5, $81, $A, $F8
	dc.b $41, $D, $A1, $E, $8
	dc.b $31, $5, $80, $14, $F8
	dc.b $31, $1, $80, $2E, $8
DATAKOCW78LZQD_1: dc.b $9
	dc.b $80, $D, $A0, $0, $F8
	dc.b $80, $D, $A0, $18, $18
	dc.b $80, $D, $80, $20, $38
	dc.b $90, $D, $80, $8, $F8
	dc.b $90, $9, $80, $30, $28
	dc.b $41, $5, $81, $A, $F8
	dc.b $41, $D, $A1, $E, $8
	dc.b $31, $5, $80, $14, $F8
	dc.b $31, $1, $80, $2E, $8
DATAKOCW78LZQD_2: dc.b $9
	dc.b $80, $D, $A0, $0, $F8
	dc.b $80, $D, $A0, $18, $18
	dc.b $80, $D, $80, $20, $38
	dc.b $90, $D, $A0, $8, $F8
	dc.b $90, $9, $80, $30, $28
	dc.b $41, $5, $81, $A, $F8
	dc.b $41, $D, $A1, $E, $8
	dc.b $31, $5, $80, $10, $F8
	dc.b $31, $1, $80, $2E, $8
DATAKOCW78LZQD_3: dc.b $9
	dc.b $80, $D, $A0, $0, $F8
	dc.b $80, $D, $A0, $18, $18
	dc.b $80, $D, $A0, $20, $38
	dc.b $90, $D, $80, $8, $F8
	dc.b $90, $9, $80, $30, $28
	dc.b $41, $5, $81, $A, $F8
	dc.b $41, $D, $A1, $E, $8
	dc.b $31, $5, $80, $10, $F8
	dc.b $31, $1, $80, $2E, $8
	even