; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Sep 27 2020 15:31:01 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATATORRYD1OR1P:
	dc.w DATATORRYD1OR1P_0-DATATORRYD1OR1P, DATATORRYD1OR1P_1-DATATORRYD1OR1P
	dc.w DATATORRYD1OR1P_2-DATATORRYD1OR1P, DATATORRYD1OR1P_3-DATATORRYD1OR1P
DATATORRYD1OR1P_0: dc.b $9
	dc.b $80, $D, $A0, $0, $F8
	dc.b $80, $D, $A0, $18, $18
	dc.b $80, $D, $80, $20, $38
	dc.b $90, $D, $A0, $8, $F8
	dc.b $90, $9, $80, $30, $28
	dc.b $41, $5, $81, $A, $F8
	dc.b $41, $D, $A1, $E, $8
	dc.b $31, $5, $80, $14, $F8
	dc.b $33, $1, $80, $2E, $A
DATATORRYD1OR1P_1: dc.b $9
	dc.b $80, $D, $A0, $0, $F8
	dc.b $80, $D, $A0, $18, $18
	dc.b $80, $D, $80, $20, $38
	dc.b $90, $D, $80, $8, $F8
	dc.b $90, $9, $80, $30, $28
	dc.b $41, $5, $81, $A, $F8
	dc.b $41, $D, $A1, $E, $8
	dc.b $31, $5, $80, $14, $F8
	dc.b $33, $1, $80, $2E, $A
DATATORRYD1OR1P_2: dc.b $9
	dc.b $80, $D, $A0, $0, $F8
	dc.b $80, $D, $A0, $18, $18
	dc.b $80, $D, $80, $20, $38
	dc.b $90, $D, $A0, $8, $F8
	dc.b $90, $9, $80, $30, $28
	dc.b $41, $5, $81, $A, $F8
	dc.b $41, $D, $A1, $E, $8
	dc.b $31, $5, $80, $10, $F8
	dc.b $33, $1, $80, $2E, $A
DATATORRYD1OR1P_3: dc.b $9
	dc.b $80, $D, $A0, $0, $F8
	dc.b $80, $D, $A0, $18, $18
	dc.b $80, $D, $A0, $20, $38
	dc.b $90, $D, $80, $8, $F8
	dc.b $90, $9, $80, $30, $28
	dc.b $41, $5, $81, $A, $F8
	dc.b $41, $D, $A1, $E, $8
	dc.b $31, $5, $80, $10, $F8
	dc.b $33, $1, $80, $2E, $A
	even