; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Sep 03 2020 18:33:26 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATASWE7UDWZI9L:
	dc.w DATASWE7UDWZI9L_0-DATASWE7UDWZI9L, DATASWE7UDWZI9L_1-DATASWE7UDWZI9L
	dc.w DATASWE7UDWZI9L_2-DATASWE7UDWZI9L, DATASWE7UDWZI9L_3-DATASWE7UDWZI9L
DATASWE7UDWZI9L_0: dc.b $C
	dc.b $EF, $0, $8, $7, $0
	dc.b $EA, $0, $0, $7, $F8
	dc.b $EA, $0, $8, $7, $0
	dc.b $EF, $0, $0, $7, $F8
	dc.b $F1, $1, $0, $0, $F8
	dc.b $1, $0, $0, $2, $F8
	dc.b $9, $1, $20, $3, $F8
	dc.b $F1, $2, $8, $0, $0
	dc.b $9, $0, $28, $3, $0
	dc.b $11, $0, $8, $4, $0
	dc.b $E7, $1, $20, $5, $F8
	dc.b $E7, $1, $28, $5, $0
DATASWE7UDWZI9L_1: dc.b $8
	dc.b $F1, $1, $0, $0, $F8
	dc.b $1, $0, $0, $2, $F8
	dc.b $9, $1, $20, $3, $F8
	dc.b $F1, $2, $8, $0, $0
	dc.b $9, $0, $28, $3, $0
	dc.b $11, $0, $8, $4, $0
	dc.b $E7, $1, $0, $5, $F8
	dc.b $E7, $1, $8, $5, $0
DATASWE7UDWZI9L_2: dc.b $0
DATASWE7UDWZI9L_3: dc.b $0
	even