; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Jun 23 2020 07:14:48 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAOGS9V7UPMZ:
	dc.w DATAOGS9V7UPMZ_0-DATAOGS9V7UPMZ, DATAOGS9V7UPMZ_1-DATAOGS9V7UPMZ
	dc.w DATAOGS9V7UPMZ_2-DATAOGS9V7UPMZ, DATAOGS9V7UPMZ_3-DATAOGS9V7UPMZ
	dc.w DATAOGS9V7UPMZ_4-DATAOGS9V7UPMZ, DATAOGS9V7UPMZ_5-DATAOGS9V7UPMZ
	dc.w DATAOGS9V7UPMZ_6-DATAOGS9V7UPMZ, DATAOGS9V7UPMZ_7-DATAOGS9V7UPMZ
	dc.w DATAOGS9V7UPMZ_8-DATAOGS9V7UPMZ, DATAOGS9V7UPMZ_9-DATAOGS9V7UPMZ
	dc.w DATAOGS9V7UPMZ_A-DATAOGS9V7UPMZ, DATAOGS9V7UPMZ_B-DATAOGS9V7UPMZ
	dc.w DATAOGS9V7UPMZ_C-DATAOGS9V7UPMZ
DATAOGS9V7UPMZ_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_1: dc.b $2
	dc.b $F5, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_2: dc.b $2
	dc.b $F5, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_3: dc.b $2
	dc.b $F5, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_4: dc.b $2
	dc.b $F5, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_5: dc.b $2
	dc.b $F5, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_6: dc.b $2
	dc.b $F5, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_7: dc.b $2
	dc.b $F5, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_8: dc.b $2
	dc.b $F5, $5, $0, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_9: dc.b $2
	dc.b $F5, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_A: dc.b $2
	dc.b $F5, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAOGS9V7UPMZ_B: dc.b $1
	dc.b $FF, $D, $0, $38, $F0
DATAOGS9V7UPMZ_C: dc.b $2
	dc.b $F5, $5, $0, $40, $F8
	dc.b $EF, $F, $0, $0, $F0
	even