; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Aug 01 2020 04:43:25 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA1S3ALSSBZ53:
	dc.w DATA1S3ALSSBZ53_0-DATA1S3ALSSBZ53, DATA1S3ALSSBZ53_1-DATA1S3ALSSBZ53
	dc.w DATA1S3ALSSBZ53_2-DATA1S3ALSSBZ53, DATA1S3ALSSBZ53_3-DATA1S3ALSSBZ53
	dc.w DATA1S3ALSSBZ53_4-DATA1S3ALSSBZ53, DATA1S3ALSSBZ53_5-DATA1S3ALSSBZ53
	dc.w DATA1S3ALSSBZ53_6-DATA1S3ALSSBZ53
DATA1S3ALSSBZ53_0: dc.b $1
	dc.b $F8, $5, $8, $0, $F8
DATA1S3ALSSBZ53_1: dc.b $1
	dc.b $F8, $5, $8, $4, $F8
DATA1S3ALSSBZ53_2: dc.b $1
	dc.b $F8, $5, $8, $8, $F8
DATA1S3ALSSBZ53_3: dc.b $0
DATA1S3ALSSBZ53_4: dc.b $0
DATA1S3ALSSBZ53_5: dc.b $0
DATA1S3ALSSBZ53_6: dc.b $0
	even