; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jun 17 2020 17:12:28 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATANTAK9DF5O9A:
	dc.w DATANTAK9DF5O9A_0-DATANTAK9DF5O9A
DATANTAK9DF5O9A_0: dc.b $6
	dc.b $F8, $1, $0, $0, $FC
	dc.b $F0, $8, $0, $2, $F4
	dc.b $8, $8, $0, $5, $F4
	dc.b $F8, $1, $0, $8, $F4
	dc.b $F8, $1, $0, $A, $4
	dc.b $10, $0, $0, $C, $FC
	even