; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Jul 23 2020 19:08:34 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAJ0CZ1CTK3B:
	dc.w DATAJ0CZ1CTK3B_0-DATAJ0CZ1CTK3B, DATAJ0CZ1CTK3B_1-DATAJ0CZ1CTK3B
	dc.w DATAJ0CZ1CTK3B_2-DATAJ0CZ1CTK3B, DATAJ0CZ1CTK3B_3-DATAJ0CZ1CTK3B
	dc.w DATAJ0CZ1CTK3B_4-DATAJ0CZ1CTK3B, DATAJ0CZ1CTK3B_5-DATAJ0CZ1CTK3B
	dc.w DATAJ0CZ1CTK3B_6-DATAJ0CZ1CTK3B, DATAJ0CZ1CTK3B_7-DATAJ0CZ1CTK3B
	dc.w DATAJ0CZ1CTK3B_8-DATAJ0CZ1CTK3B, DATAJ0CZ1CTK3B_9-DATAJ0CZ1CTK3B
	dc.w DATAJ0CZ1CTK3B_A-DATAJ0CZ1CTK3B, DATAJ0CZ1CTK3B_B-DATAJ0CZ1CTK3B
DATAJ0CZ1CTK3B_0: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATAJ0CZ1CTK3B_1: dc.b $1
	dc.b $F8, $5, $8, $12, $F8
DATAJ0CZ1CTK3B_2: dc.b $1
	dc.b $F8, $5, $0, $4, $F8
DATAJ0CZ1CTK3B_3: dc.b $1
	dc.b $F8, $1, $8, $16, $FC
DATAJ0CZ1CTK3B_4: dc.b $1
	dc.b $F8, $1, $0, $8, $FC
DATAJ0CZ1CTK3B_5: dc.b $1
	dc.b $F8, $1, $0, $16, $FC
DATAJ0CZ1CTK3B_6: dc.b $1
	dc.b $F8, $5, $8, $4, $F8
DATAJ0CZ1CTK3B_7: dc.b $1
	dc.b $F8, $5, $0, $12, $F8
DATAJ0CZ1CTK3B_8: dc.b $1
	dc.b $F8, $5, $0, $A, $F8
DATAJ0CZ1CTK3B_9: dc.b $1
	dc.b $F8, $5, $18, $A, $F8
DATAJ0CZ1CTK3B_A: dc.b $1
	dc.b $F8, $5, $8, $A, $F8
DATAJ0CZ1CTK3B_B: dc.b $1
	dc.b $F8, $5, $10, $A, $F8
	even