; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu May 28 2020 09:01:38 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAOEYN4WC4ARE:
	dc.w $0, DATAOEYN4WC4ARE_1-DATAOEYN4WC4ARE
	dc.w DATAOEYN4WC4ARE_2-DATAOEYN4WC4ARE, DATAOEYN4WC4ARE_3-DATAOEYN4WC4ARE
	dc.w DATAOEYN4WC4ARE_4-DATAOEYN4WC4ARE, DATAOEYN4WC4ARE_5-DATAOEYN4WC4ARE
	dc.w DATAOEYN4WC4ARE_6-DATAOEYN4WC4ARE, DATAOEYN4WC4ARE_7-DATAOEYN4WC4ARE
DATAOEYN4WC4ARE_1: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $E8, $A, $0, $9, $0
	dc.b $0, $A, $10, $0, $E8
	dc.b $0, $A, $10, $9, $0
DATAOEYN4WC4ARE_2: dc.b $4
	dc.b $E8, $A, $8, $12, $E9
	dc.b $E8, $A, $0, $12, $0
	dc.b $0, $A, $18, $12, $E9
	dc.b $0, $A, $10, $12, $0
DATAOEYN4WC4ARE_3: dc.b $4
	dc.b $E8, $A, $8, $9, $E8
	dc.b $E8, $A, $8, $0, $0
	dc.b $0, $A, $18, $9, $E8
	dc.b $0, $A, $18, $0, $0
DATAOEYN4WC4ARE_4: dc.b $4
	dc.b $E8, $A, $0, $0, $E8
	dc.b $E8, $A, $0, $9, $0
	dc.b $0, $A, $18, $9, $E8
	dc.b $0, $A, $18, $0, $0
DATAOEYN4WC4ARE_5: dc.b $4
	dc.b $E8, $A, $8, $9, $E8
	dc.b $E8, $A, $8, $0, $0
	dc.b $0, $A, $10, $0, $E8
	dc.b $0, $A, $10, $9, $0
DATAOEYN4WC4ARE_6: dc.b $4
	dc.b $E8, $A, $0, $12, $E8
	dc.b $E8, $A, $0, $1B, $0
	dc.b $0, $A, $18, $1B, $E8
	dc.b $0, $A, $18, $12, $0
DATAOEYN4WC4ARE_7: dc.b $4
	dc.b $E8, $A, $8, $1B, $E8
	dc.b $E8, $A, $8, $12, $0
	dc.b $0, $A, $10, $12, $E8
	dc.b $0, $A, $10, $1B, $0
	even