; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Nov 24 2020 19:30:21 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAB8PWBD9HLQR:
	dc.w DATAB8PWBD9HLQR_0-DATAB8PWBD9HLQR, DATAB8PWBD9HLQR_1-DATAB8PWBD9HLQR
	dc.w DATAB8PWBD9HLQR_2-DATAB8PWBD9HLQR, DATAB8PWBD9HLQR_3-DATAB8PWBD9HLQR
	dc.w DATAB8PWBD9HLQR_4-DATAB8PWBD9HLQR
DATAB8PWBD9HLQR_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $C, $FC
DATAB8PWBD9HLQR_1: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $10, $1, $0, $10, $FC
DATAB8PWBD9HLQR_2: dc.b $2
	dc.b $F0, $3, $0, $0, $FC
	dc.b $10, $1, $8, $4, $FC
DATAB8PWBD9HLQR_3: dc.b $2
	dc.b $F0, $F, $8, $0, $F0
	dc.b $10, $1, $8, $10, $FC
DATAB8PWBD9HLQR_4: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $0, $C, $0
	dc.b $10, $1, $0, $18, $FC
	even