; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Aug 12 2020 14:05:14 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATAKAQ4FZBHIW:
	dc.w DATAKAQ4FZBHIW_0-DATAKAQ4FZBHIW, DATAKAQ4FZBHIW_1-DATAKAQ4FZBHIW
	dc.w DATAKAQ4FZBHIW_2-DATAKAQ4FZBHIW, DATAKAQ4FZBHIW_3-DATAKAQ4FZBHIW
	dc.w DATAKAQ4FZBHIW_4-DATAKAQ4FZBHIW
DATAKAQ4FZBHIW_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $38, $FC
DATAKAQ4FZBHIW_1: dc.b $2
	dc.b $F0, $F, $0, $C, $F0
	dc.b $10, $1, $0, $38, $FC
DATAKAQ4FZBHIW_2: dc.b $2
	dc.b $F0, $3, $0, $1C, $FC
	dc.b $10, $1, $8, $38, $FC
DATAKAQ4FZBHIW_3: dc.b $2
	dc.b $F0, $F, $8, $C, $F0
	dc.b $10, $1, $8, $38, $FC
DATAKAQ4FZBHIW_4: dc.b $3
	dc.b $F0, $B, $0, $20, $E8
	dc.b $F0, $B, $0, $2C, $0
	dc.b $10, $1, $0, $38, $FC
	even