; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Sep 07 2020 07:18:30 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATACL7Q676NQH7:
	dc.w $0, DATACL7Q676NQH7_1-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_2-DATACL7Q676NQH7, DATACL7Q676NQH7_3-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_4-DATACL7Q676NQH7, DATACL7Q676NQH7_5-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_6-DATACL7Q676NQH7, DATACL7Q676NQH7_7-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_8-DATACL7Q676NQH7, DATACL7Q676NQH7_9-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_A-DATACL7Q676NQH7, DATACL7Q676NQH7_B-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_C-DATACL7Q676NQH7, DATACL7Q676NQH7_D-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_E-DATACL7Q676NQH7, DATACL7Q676NQH7_F-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_10-DATACL7Q676NQH7, DATACL7Q676NQH7_11-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_12-DATACL7Q676NQH7, DATACL7Q676NQH7_13-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_14-DATACL7Q676NQH7, DATACL7Q676NQH7_15-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_16-DATACL7Q676NQH7, DATACL7Q676NQH7_17-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_18-DATACL7Q676NQH7, DATACL7Q676NQH7_19-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_1A-DATACL7Q676NQH7, DATACL7Q676NQH7_1B-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_1C-DATACL7Q676NQH7, DATACL7Q676NQH7_1D-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_1E-DATACL7Q676NQH7, DATACL7Q676NQH7_1F-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_20-DATACL7Q676NQH7, DATACL7Q676NQH7_21-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_22-DATACL7Q676NQH7, DATACL7Q676NQH7_23-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_24-DATACL7Q676NQH7, DATACL7Q676NQH7_25-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_26-DATACL7Q676NQH7, DATACL7Q676NQH7_27-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_28-DATACL7Q676NQH7, DATACL7Q676NQH7_29-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_2A-DATACL7Q676NQH7, DATACL7Q676NQH7_2B-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_2C-DATACL7Q676NQH7, DATACL7Q676NQH7_2D-DATACL7Q676NQH7
	dc.w DATACL7Q676NQH7_2E-DATACL7Q676NQH7, DATACL7Q676NQH7_2F-DATACL7Q676NQH7
DATACL7Q676NQH7_1: dc.b $7
	dc.b $F0, $0, $20, $0, $2
	dc.b $ED, $8, $0, $1, $F0
	dc.b $F5, $D, $0, $4, $F0
	dc.b $5, $8, $0, $C, $F0
	dc.b $D, $8, $0, $F, $F8
	dc.b $D, $0, $0, $12, $F0
	dc.b $5, $0, $0, $13, $8
DATACL7Q676NQH7_2: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATACL7Q676NQH7_3: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATACL7Q676NQH7_4: dc.b $3
	dc.b $FD, $A, $0, $0, $F3
	dc.b $F7, $0, $0, $9, $B
	dc.b $ED, $9, $0, $A, $F3
DATACL7Q676NQH7_5: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATACL7Q676NQH7_6: dc.b $3
	dc.b $FC, $E, $0, $0, $EB
	dc.b $F6, $0, $0, $C, $B
	dc.b $EC, $9, $0, $D, $F3
DATACL7Q676NQH7_7: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATACL7Q676NQH7_8: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATACL7Q676NQH7_9: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATACL7Q676NQH7_A: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATACL7Q676NQH7_B: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATACL7Q676NQH7_C: dc.b $2
	dc.b $0, $9, $20, $10, $F1
	dc.b $F1, $F, $0, $0, $F0
DATACL7Q676NQH7_D: dc.b $2
	dc.b $F1, $B, $20, $10, $F1
	dc.b $F2, $F, $0, $0, $F1
DATACL7Q676NQH7_E: dc.b $2
	dc.b $F1, $5, $20, $10, $F0
	dc.b $EE, $F, $0, $0, $F0
DATACL7Q676NQH7_F: dc.b $2
	dc.b $FF, $D, $20, $10, $F4
	dc.b $F1, $F, $0, $0, $F1
DATACL7Q676NQH7_10: dc.b $3
	dc.b $F, $0, $20, $18, $FD
	dc.b $FF, $D, $20, $0, $F1
	dc.b $F0, $F, $0, $8, $F1
DATACL7Q676NQH7_11: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATACL7Q676NQH7_12: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATACL7Q676NQH7_13: dc.b $4
	dc.b $EF, $E, $0, $0, $EC
	dc.b $F7, $1, $0, $C, $C
	dc.b $7, $C, $0, $E, $F4
	dc.b $EF, $0, $0, $12, $C
DATACL7Q676NQH7_14: dc.b $4
	dc.b $EB, $9, $8, $0, $F4
	dc.b $FB, $9, $8, $6, $FC
	dc.b $FB, $6, $8, $C, $EC
	dc.b $B, $4, $8, $12, $4
DATACL7Q676NQH7_15: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATACL7Q676NQH7_16: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $8, $0, $C, $F4
DATACL7Q676NQH7_17: dc.b $5
	dc.b $0, $C, $0, $0, $EC
	dc.b $8, $5, $0, $4, $F4
	dc.b $8, $0, $0, $8, $4
	dc.b $E8, $A, $0, $9, $F4
	dc.b $F0, $1, $0, $12, $C
DATACL7Q676NQH7_18: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $C, $0, $B, $EC
	dc.b $8, $5, $0, $F, $F4
	dc.b $8, $0, $0, $13, $4
DATACL7Q676NQH7_19: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
	dc.b $10, $4, $0, $F, $F4
DATACL7Q676NQH7_1A: dc.b $3
	dc.b $8, $8, $0, $0, $F4
	dc.b $10, $4, $0, $3, $F4
	dc.b $E8, $B, $0, $5, $F4
DATACL7Q676NQH7_1B: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
DATACL7Q676NQH7_1C: dc.b $2
	dc.b $E8, $F, $0, $0, $F4
	dc.b $8, $8, $0, $10, $F4
DATACL7Q676NQH7_1D: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATACL7Q676NQH7_1E: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATACL7Q676NQH7_1F: dc.b $4
	dc.b $FC, $D, $0, $0, $F4
	dc.b $EC, $9, $0, $8, $F4
	dc.b $4, $0, $0, $E, $EC
	dc.b $C, $4, $0, $F, $4
DATACL7Q676NQH7_20: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATACL7Q676NQH7_21: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATACL7Q676NQH7_22: dc.b $3
	dc.b $F4, $D, $8, $0, $EC
	dc.b $FC, $5, $8, $8, $C
	dc.b $4, $8, $8, $C, $F4
DATACL7Q676NQH7_23: dc.b $3
	dc.b $F4, $D, $0, $0, $EC
	dc.b $FC, $0, $0, $8, $C
	dc.b $4, $C, $0, $9, $F4
DATACL7Q676NQH7_24: dc.b $3
	dc.b $F4, $D, $8, $0, $F4
	dc.b $FC, $0, $8, $8, $EC
	dc.b $4, $C, $8, $9, $EC
DATACL7Q676NQH7_25: dc.b $8
	dc.b $E8, $1, $0, $0, $C
	dc.b $10, $0, $0, $2, $F4
	dc.b $8, $8, $0, $3, $F4
	dc.b $10, $0, $0, $6, $FC
	dc.b $FC, $0, $0, $7, $C
	dc.b $8, $0, $0, $8, $C
	dc.b $E8, $9, $0, $9, $F4
	dc.b $F8, $D, $0, $F, $EC
DATACL7Q676NQH7_26: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $8, $0, $10, $F4
	dc.b $10, $0, $0, $13, $FC
	dc.b $10, $4, $0, $14, $EC
	dc.b $8, $0, $0, $16, $C
DATACL7Q676NQH7_27: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATACL7Q676NQH7_28: dc.b $8
	dc.b $FD, $5, $0, $13, $F1
	dc.b $D, $8, $0, $0, $F8
	dc.b $D, $0, $0, $3, $F0
	dc.b $F5, $D, $0, $4, $F0
	dc.b $ED, $8, $0, $C, $F0
	dc.b $5, $0, $0, $F, $0
	dc.b $5, $0, $0, $10, $8
	dc.b $5, $4, $0, $11, $F0
DATACL7Q676NQH7_29: dc.b $8
	dc.b $FD, $5, $0, $0, $F1
	dc.b $D, $8, $0, $4, $F8
	dc.b $D, $0, $0, $7, $F0
	dc.b $ED, $8, $0, $8, $F0
	dc.b $5, $0, $0, $B, $0
	dc.b $5, $0, $0, $C, $8
	dc.b $5, $4, $0, $D, $F0
	dc.b $F5, $9, $0, $F, $F0
DATACL7Q676NQH7_2A: dc.b $6
	dc.b $F6, $6, $0, $0, $F0
	dc.b $ED, $8, $0, $6, $F0
	dc.b $D, $8, $0, $9, $F8
	dc.b $D, $0, $0, $C, $F0
	dc.b $5, $8, $0, $D, $F0
	dc.b $F5, $9, $0, $10, $F0
DATACL7Q676NQH7_2B: dc.b $7
	dc.b $F9, $5, $0, $0, $EA
	dc.b $1, $0, $0, $4, $FA
	dc.b $ED, $8, $0, $5, $F0
	dc.b $D, $8, $0, $8, $F8
	dc.b $D, $0, $0, $B, $F0
	dc.b $5, $8, $0, $C, $F0
	dc.b $F5, $9, $0, $F, $F0
DATACL7Q676NQH7_2C: dc.b $6
	dc.b $F6, $6, $0, $0, $F0
	dc.b $ED, $8, $0, $6, $F0
	dc.b $D, $0, $0, $9, $F0
	dc.b $D, $8, $0, $A, $F8
	dc.b $5, $8, $0, $D, $F0
	dc.b $F5, $9, $0, $10, $F0
DATACL7Q676NQH7_2D: dc.b $7
	dc.b $F9, $5, $0, $0, $EA
	dc.b $1, $0, $0, $4, $FA
	dc.b $ED, $8, $0, $5, $F0
	dc.b $D, $0, $0, $8, $F0
	dc.b $5, $8, $0, $9, $F0
	dc.b $F5, $9, $0, $C, $F0
	dc.b $D, $8, $0, $12, $F8
DATACL7Q676NQH7_2E: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
DATACL7Q676NQH7_2F: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
	even