; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Sep 14 2020 19:38:53 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATANGHR43WHLC:
	dc.w $0, DATANGHR43WHLC_1-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_2-DATANGHR43WHLC, DATANGHR43WHLC_3-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_4-DATANGHR43WHLC, DATANGHR43WHLC_5-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_6-DATANGHR43WHLC, DATANGHR43WHLC_7-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_8-DATANGHR43WHLC, DATANGHR43WHLC_9-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_A-DATANGHR43WHLC, DATANGHR43WHLC_B-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_C-DATANGHR43WHLC, DATANGHR43WHLC_D-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_E-DATANGHR43WHLC, DATANGHR43WHLC_F-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_10-DATANGHR43WHLC, DATANGHR43WHLC_11-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_12-DATANGHR43WHLC, DATANGHR43WHLC_13-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_14-DATANGHR43WHLC, DATANGHR43WHLC_15-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_16-DATANGHR43WHLC, DATANGHR43WHLC_17-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_18-DATANGHR43WHLC, DATANGHR43WHLC_19-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_1A-DATANGHR43WHLC, DATANGHR43WHLC_1B-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_1C-DATANGHR43WHLC, DATANGHR43WHLC_1D-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_1E-DATANGHR43WHLC, DATANGHR43WHLC_1F-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_20-DATANGHR43WHLC, DATANGHR43WHLC_21-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_22-DATANGHR43WHLC, DATANGHR43WHLC_23-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_24-DATANGHR43WHLC, DATANGHR43WHLC_25-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_26-DATANGHR43WHLC, DATANGHR43WHLC_27-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_28-DATANGHR43WHLC, DATANGHR43WHLC_29-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_2A-DATANGHR43WHLC, DATANGHR43WHLC_2B-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_2C-DATANGHR43WHLC, DATANGHR43WHLC_2D-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_2E-DATANGHR43WHLC, DATANGHR43WHLC_2F-DATANGHR43WHLC
	dc.w DATANGHR43WHLC_30-DATANGHR43WHLC
DATANGHR43WHLC_1: dc.b $7
	dc.b $F0, $0, $20, $0, $2
	dc.b $ED, $8, $0, $1, $F0
	dc.b $F5, $D, $0, $4, $F0
	dc.b $5, $8, $0, $C, $F0
	dc.b $D, $8, $0, $F, $F8
	dc.b $D, $0, $0, $12, $F0
	dc.b $5, $0, $0, $13, $8
DATANGHR43WHLC_2: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATANGHR43WHLC_3: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATANGHR43WHLC_4: dc.b $3
	dc.b $FD, $A, $0, $0, $F3
	dc.b $F7, $0, $0, $9, $B
	dc.b $ED, $9, $0, $A, $F3
DATANGHR43WHLC_5: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATANGHR43WHLC_6: dc.b $3
	dc.b $FC, $E, $0, $0, $EB
	dc.b $F6, $0, $0, $C, $B
	dc.b $EC, $9, $0, $D, $F3
DATANGHR43WHLC_7: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATANGHR43WHLC_8: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATANGHR43WHLC_9: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATANGHR43WHLC_A: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATANGHR43WHLC_B: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATANGHR43WHLC_C: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
DATANGHR43WHLC_D: dc.b $1
	dc.b $F2, $F, $0, $0, $F1
DATANGHR43WHLC_E: dc.b $1
	dc.b $EE, $F, $0, $0, $F0
DATANGHR43WHLC_F: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATANGHR43WHLC_10: dc.b $1
	dc.b $F0, $F, $0, $0, $F1
DATANGHR43WHLC_11: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATANGHR43WHLC_12: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATANGHR43WHLC_13: dc.b $4
	dc.b $EF, $E, $0, $0, $EC
	dc.b $F7, $1, $0, $C, $C
	dc.b $7, $C, $0, $E, $F4
	dc.b $EF, $0, $0, $12, $C
DATANGHR43WHLC_14: dc.b $4
	dc.b $EB, $9, $8, $0, $F4
	dc.b $FB, $9, $8, $6, $FC
	dc.b $FB, $6, $8, $C, $EC
	dc.b $B, $4, $8, $12, $4
DATANGHR43WHLC_15: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATANGHR43WHLC_16: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $8, $0, $C, $F4
DATANGHR43WHLC_17: dc.b $5
	dc.b $0, $C, $0, $0, $EC
	dc.b $8, $5, $0, $4, $F4
	dc.b $8, $0, $0, $8, $4
	dc.b $E8, $A, $0, $9, $F4
	dc.b $F0, $1, $0, $12, $C
DATANGHR43WHLC_18: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $C, $0, $B, $EC
	dc.b $8, $5, $0, $F, $F4
	dc.b $8, $0, $0, $13, $4
DATANGHR43WHLC_19: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
	dc.b $10, $4, $0, $F, $F4
DATANGHR43WHLC_1A: dc.b $3
	dc.b $8, $8, $0, $0, $F4
	dc.b $10, $4, $0, $3, $F4
	dc.b $E8, $B, $0, $5, $F4
DATANGHR43WHLC_1B: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
DATANGHR43WHLC_1C: dc.b $2
	dc.b $E8, $F, $0, $0, $F4
	dc.b $8, $8, $0, $10, $F4
DATANGHR43WHLC_1D: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATANGHR43WHLC_1E: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATANGHR43WHLC_1F: dc.b $4
	dc.b $FC, $D, $0, $0, $F4
	dc.b $EC, $9, $0, $8, $F4
	dc.b $4, $0, $0, $E, $EC
	dc.b $C, $4, $0, $F, $4
DATANGHR43WHLC_20: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATANGHR43WHLC_21: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATANGHR43WHLC_22: dc.b $3
	dc.b $F4, $D, $8, $0, $EC
	dc.b $FC, $5, $8, $8, $C
	dc.b $4, $8, $8, $C, $F4
DATANGHR43WHLC_23: dc.b $3
	dc.b $F4, $D, $0, $0, $EC
	dc.b $FC, $0, $0, $8, $C
	dc.b $4, $C, $0, $9, $F4
DATANGHR43WHLC_24: dc.b $3
	dc.b $F4, $D, $8, $0, $F4
	dc.b $FC, $0, $8, $8, $EC
	dc.b $4, $C, $8, $9, $EC
DATANGHR43WHLC_25: dc.b $8
	dc.b $E8, $1, $0, $0, $C
	dc.b $10, $0, $0, $2, $F4
	dc.b $8, $8, $0, $3, $F4
	dc.b $10, $0, $0, $6, $FC
	dc.b $FC, $0, $0, $7, $C
	dc.b $8, $0, $0, $8, $C
	dc.b $E8, $9, $0, $9, $F4
	dc.b $F8, $D, $0, $F, $EC
DATANGHR43WHLC_26: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $8, $0, $10, $F4
	dc.b $10, $0, $0, $13, $FC
	dc.b $10, $4, $0, $14, $EC
	dc.b $8, $0, $0, $16, $C
DATANGHR43WHLC_27: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATANGHR43WHLC_28: dc.b $8
	dc.b $FD, $5, $0, $13, $F1
	dc.b $D, $8, $0, $0, $F8
	dc.b $D, $0, $0, $3, $F0
	dc.b $F5, $D, $0, $4, $F0
	dc.b $ED, $8, $0, $C, $F0
	dc.b $5, $0, $0, $F, $0
	dc.b $5, $0, $0, $10, $8
	dc.b $5, $4, $0, $11, $F0
DATANGHR43WHLC_29: dc.b $8
	dc.b $FD, $5, $0, $0, $F1
	dc.b $D, $8, $0, $4, $F8
	dc.b $D, $0, $0, $7, $F0
	dc.b $ED, $8, $0, $8, $F0
	dc.b $5, $0, $0, $B, $0
	dc.b $5, $0, $0, $C, $8
	dc.b $5, $4, $0, $D, $F0
	dc.b $F5, $9, $0, $F, $F0
DATANGHR43WHLC_2A: dc.b $6
	dc.b $F6, $6, $0, $0, $F0
	dc.b $ED, $8, $0, $6, $F0
	dc.b $D, $8, $0, $9, $F8
	dc.b $D, $0, $0, $C, $F0
	dc.b $5, $8, $0, $D, $F0
	dc.b $F5, $9, $0, $10, $F0
DATANGHR43WHLC_2B: dc.b $7
	dc.b $F9, $5, $0, $0, $EA
	dc.b $1, $0, $0, $4, $FA
	dc.b $ED, $8, $0, $5, $F0
	dc.b $D, $8, $0, $8, $F8
	dc.b $D, $0, $0, $B, $F0
	dc.b $5, $8, $0, $C, $F0
	dc.b $F5, $9, $0, $F, $F0
DATANGHR43WHLC_2C: dc.b $6
	dc.b $F6, $6, $0, $0, $F0
	dc.b $ED, $8, $0, $6, $F0
	dc.b $D, $0, $0, $9, $F0
	dc.b $D, $8, $0, $A, $F8
	dc.b $5, $8, $0, $D, $F0
	dc.b $F5, $9, $0, $10, $F0
DATANGHR43WHLC_2D: dc.b $7
	dc.b $F9, $5, $0, $0, $EA
	dc.b $1, $0, $0, $4, $FA
	dc.b $ED, $8, $0, $5, $F0
	dc.b $D, $0, $0, $8, $F0
	dc.b $5, $8, $0, $9, $F0
	dc.b $F5, $9, $0, $C, $F0
	dc.b $D, $8, $0, $12, $F8
DATANGHR43WHLC_2E: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
DATANGHR43WHLC_2F: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
DATANGHR43WHLC_30: dc.b $4
	dc.b $C, $0, $20, $13, $FD
	dc.b $F4, $3, $20, $F, $F5
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
	even