; ================================================================================
; Sprite Mappings - generated by Flex 2 Tue Sep 29 2020 22:02:15 GMT-0400 (Eastern Daylight Time)
; ================================================================================

DATA6T5KTUXAH6O:
	dc.w $0, DATA6T5KTUXAH6O_1-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_2-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_3-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_4-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_5-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_6-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_7-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_8-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_9-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_A-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_B-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_C-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_D-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_E-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_F-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_10-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_11-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_12-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_13-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_14-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_15-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_16-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_17-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_18-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_19-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_1A-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_1B-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_1C-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_1D-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_1E-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_1F-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_20-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_21-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_22-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_23-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_24-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_25-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_26-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_27-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_28-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_29-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_2A-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_2B-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_2C-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_2D-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_2E-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_2F-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_30-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_31-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_32-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_33-DATA6T5KTUXAH6O
	dc.w DATA6T5KTUXAH6O_34-DATA6T5KTUXAH6O, DATA6T5KTUXAH6O_35-DATA6T5KTUXAH6O
DATA6T5KTUXAH6O_1: dc.b $7
	dc.b $F0, $0, $20, $0, $2
	dc.b $ED, $8, $0, $1, $F0
	dc.b $F5, $D, $0, $4, $F0
	dc.b $5, $8, $0, $C, $F0
	dc.b $D, $8, $0, $F, $F8
	dc.b $D, $0, $0, $12, $F0
	dc.b $5, $0, $0, $13, $8
DATA6T5KTUXAH6O_2: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATA6T5KTUXAH6O_3: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATA6T5KTUXAH6O_4: dc.b $3
	dc.b $FD, $A, $0, $0, $F3
	dc.b $F7, $0, $0, $9, $B
	dc.b $ED, $9, $0, $A, $F3
DATA6T5KTUXAH6O_5: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATA6T5KTUXAH6O_6: dc.b $3
	dc.b $FC, $E, $0, $0, $EB
	dc.b $F6, $0, $0, $C, $B
	dc.b $EC, $9, $0, $D, $F3
DATA6T5KTUXAH6O_7: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATA6T5KTUXAH6O_8: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATA6T5KTUXAH6O_9: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATA6T5KTUXAH6O_A: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATA6T5KTUXAH6O_B: dc.b $3
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
	dc.b $F8, $0, $0, $12, $C
DATA6T5KTUXAH6O_C: dc.b $2
	dc.b $0, $9, $20, $10, $F1
	dc.b $F1, $F, $0, $0, $F0
DATA6T5KTUXAH6O_D: dc.b $2
	dc.b $F1, $B, $20, $10, $F1
	dc.b $F2, $F, $0, $0, $F1
DATA6T5KTUXAH6O_E: dc.b $2
	dc.b $F1, $5, $20, $10, $F0
	dc.b $EE, $F, $0, $0, $F0
DATA6T5KTUXAH6O_F: dc.b $2
	dc.b $FF, $D, $20, $10, $F4
	dc.b $F1, $F, $0, $0, $F1
DATA6T5KTUXAH6O_10: dc.b $3
	dc.b $F, $0, $20, $18, $FD
	dc.b $FF, $D, $20, $10, $F1
	dc.b $F0, $F, $0, $0, $F1
DATA6T5KTUXAH6O_11: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $10, $0, $0, $10, $F4
	dc.b $8, $8, $0, $11, $F4
	dc.b $10, $0, $0, $14, $FC
	dc.b $10, $0, $0, $15, $4
DATA6T5KTUXAH6O_12: dc.b $9
	dc.b $E8, $9, $0, $0, $F4
	dc.b $FC, $0, $0, $6, $EC
	dc.b $F8, $9, $0, $7, $F4
	dc.b $10, $0, $0, $D, $F4
	dc.b $8, $8, $0, $E, $F4
	dc.b $10, $0, $0, $11, $FC
	dc.b $10, $0, $0, $12, $4
	dc.b $FE, $0, $0, $13, $C
	dc.b $FE, $0, $0, $14, $14
DATA6T5KTUXAH6O_13: dc.b $4
	dc.b $EF, $E, $0, $0, $EC
	dc.b $F7, $1, $0, $C, $C
	dc.b $7, $C, $0, $E, $F4
	dc.b $EF, $0, $0, $12, $C
DATA6T5KTUXAH6O_14: dc.b $4
	dc.b $EB, $9, $8, $0, $F4
	dc.b $FB, $9, $8, $6, $FC
	dc.b $FB, $6, $8, $C, $EC
	dc.b $B, $4, $8, $12, $4
DATA6T5KTUXAH6O_15: dc.b $2
	dc.b $EF, $F, $0, $0, $F0
	dc.b $F, $C, $0, $10, $F0
DATA6T5KTUXAH6O_16: dc.b $2
	dc.b $EF, $B, $0, $0, $F4
	dc.b $F, $8, $0, $C, $F4
DATA6T5KTUXAH6O_17: dc.b $5
	dc.b $0, $C, $0, $0, $EC
	dc.b $8, $5, $0, $4, $F4
	dc.b $8, $0, $0, $8, $4
	dc.b $E8, $A, $0, $9, $F4
	dc.b $F0, $1, $0, $12, $C
DATA6T5KTUXAH6O_18: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $C, $0, $B, $EC
	dc.b $8, $5, $0, $F, $F4
	dc.b $8, $0, $0, $13, $4
DATA6T5KTUXAH6O_19: dc.b $3
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
	dc.b $10, $4, $0, $F, $F4
DATA6T5KTUXAH6O_1A: dc.b $3
	dc.b $8, $8, $0, $0, $F4
	dc.b $10, $4, $0, $3, $F4
	dc.b $E8, $B, $0, $5, $F4
DATA6T5KTUXAH6O_1B: dc.b $2
	dc.b $E8, $B, $0, $0, $F4
	dc.b $8, $8, $0, $C, $F4
DATA6T5KTUXAH6O_1C: dc.b $2
	dc.b $E8, $F, $0, $0, $F4
	dc.b $8, $8, $0, $10, $F4
DATA6T5KTUXAH6O_1D: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATA6T5KTUXAH6O_1E: dc.b $1
	dc.b $F3, $F, $0, $0, $F3
DATA6T5KTUXAH6O_1F: dc.b $4
	dc.b $FC, $D, $0, $0, $F4
	dc.b $EC, $9, $0, $8, $F4
	dc.b $4, $0, $0, $E, $EC
	dc.b $C, $4, $0, $F, $4
DATA6T5KTUXAH6O_20: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATA6T5KTUXAH6O_21: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATA6T5KTUXAH6O_22: dc.b $3
	dc.b $F4, $D, $8, $0, $EC
	dc.b $FC, $5, $8, $8, $C
	dc.b $4, $8, $8, $C, $F4
DATA6T5KTUXAH6O_23: dc.b $3
	dc.b $F4, $D, $0, $0, $EC
	dc.b $FC, $0, $0, $8, $C
	dc.b $4, $C, $0, $9, $F4
DATA6T5KTUXAH6O_24: dc.b $3
	dc.b $F4, $D, $8, $0, $F4
	dc.b $FC, $0, $8, $8, $EC
	dc.b $4, $C, $8, $9, $EC
DATA6T5KTUXAH6O_25: dc.b $8
	dc.b $E8, $1, $0, $0, $C
	dc.b $10, $0, $0, $2, $F4
	dc.b $8, $8, $0, $3, $F4
	dc.b $10, $0, $0, $6, $FC
	dc.b $FC, $0, $0, $7, $C
	dc.b $8, $0, $0, $8, $C
	dc.b $E8, $9, $0, $9, $F4
	dc.b $F8, $D, $0, $F, $EC
DATA6T5KTUXAH6O_26: dc.b $7
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $8, $0, $10, $F4
	dc.b $10, $0, $0, $13, $FC
	dc.b $10, $4, $0, $14, $EC
	dc.b $8, $0, $0, $16, $C
DATA6T5KTUXAH6O_27: dc.b $4
	dc.b $FB, $9, $0, $0, $EC
	dc.b $FB, $6, $0, $6, $4
	dc.b $B, $4, $0, $C, $EC
	dc.b $EB, $9, $0, $E, $F4
DATA6T5KTUXAH6O_28: dc.b $8
	dc.b $FD, $5, $0, $13, $F1
	dc.b $D, $8, $0, $0, $F8
	dc.b $D, $0, $0, $3, $F0
	dc.b $F5, $D, $0, $4, $F0
	dc.b $ED, $8, $0, $C, $F0
	dc.b $5, $0, $0, $F, $0
	dc.b $5, $0, $0, $10, $8
	dc.b $5, $4, $0, $11, $F0
DATA6T5KTUXAH6O_29: dc.b $8
	dc.b $FD, $5, $0, $0, $F1
	dc.b $D, $8, $0, $4, $F8
	dc.b $D, $0, $0, $7, $F0
	dc.b $ED, $8, $0, $8, $F0
	dc.b $5, $0, $0, $B, $0
	dc.b $5, $0, $0, $C, $8
	dc.b $5, $4, $0, $D, $F0
	dc.b $F5, $9, $0, $F, $F0
DATA6T5KTUXAH6O_2A: dc.b $6
	dc.b $F6, $6, $0, $0, $F0
	dc.b $ED, $8, $0, $6, $F0
	dc.b $D, $8, $0, $9, $F8
	dc.b $D, $0, $0, $C, $F0
	dc.b $5, $8, $0, $D, $F0
	dc.b $F5, $9, $0, $10, $F0
DATA6T5KTUXAH6O_2B: dc.b $7
	dc.b $F9, $5, $0, $0, $EA
	dc.b $1, $0, $0, $4, $FA
	dc.b $ED, $8, $0, $5, $F0
	dc.b $D, $8, $0, $8, $F8
	dc.b $D, $0, $0, $B, $F0
	dc.b $5, $8, $0, $C, $F0
	dc.b $F5, $9, $0, $F, $F0
DATA6T5KTUXAH6O_2C: dc.b $6
	dc.b $F6, $6, $0, $0, $F0
	dc.b $ED, $8, $0, $6, $F0
	dc.b $D, $0, $0, $9, $F0
	dc.b $D, $8, $0, $A, $F8
	dc.b $5, $8, $0, $D, $F0
	dc.b $F5, $9, $0, $10, $F0
DATA6T5KTUXAH6O_2D: dc.b $7
	dc.b $F9, $5, $0, $0, $EA
	dc.b $1, $0, $0, $4, $FA
	dc.b $ED, $8, $0, $5, $F0
	dc.b $D, $0, $0, $8, $F0
	dc.b $5, $8, $0, $9, $F0
	dc.b $F5, $9, $0, $C, $F0
	dc.b $D, $8, $0, $12, $F8
DATA6T5KTUXAH6O_2E: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
DATA6T5KTUXAH6O_2F: dc.b $3
	dc.b $EC, $B, $0, $0, $EC
	dc.b $F4, $3, $0, $C, $4
	dc.b $C, $4, $0, $10, $F4
DATA6T5KTUXAH6O_30: dc.b $4
	dc.b $C, $0, $20, $13, $FD
	dc.b $F4, $3, $20, $F, $F5
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATA6T5KTUXAH6O_31: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATA6T5KTUXAH6O_32: dc.b $1
	dc.b $EF, $F, $0, $0, $F2
DATA6T5KTUXAH6O_33: dc.b $1
	dc.b $F1, $F, $0, $0, $F2
DATA6T5KTUXAH6O_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F2
DATA6T5KTUXAH6O_35: dc.b $1
	dc.b $F1, $F, $0, $0, $F0
	even